import React from 'react';

const IndexDuplicate1Section__structures7 = () => {
    return (
        <section className="relative content-center items-center box-border gap-x-0 flex flex-col shrink-0 h-min justify-start gap-y-0 w-full scroll-mt-[84px]">
  <div className="relative content-center items-center box-border gap-x-10 flex flex-col shrink-0 h-min justify-start max-w-[1200px] gap-y-10 w-full overflow-hidden px-4 py-16 md:gap-x-12 md:gap-y-12 md:px-6 md:py-24">
    <div className="relative content-start items-start box-border gap-x-4 flex flex-col shrink-0 h-min justify-start max-w-[920px] gap-y-4 translate-y-16 w-full overflow-hidden px-0 md:px-6">
      <div className="box-content block md:aspect-auto md:box-border md:contents md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
        <div className="static box-content shrink min-h-0 min-w-0 md:relative md:aspect-auto md:box-border md:shrink-0 md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
          <div className="static [align-items:normal] box-content gap-x-[normal] block h-auto justify-normal gap-y-[normal] w-auto md:relative md:content-center md:items-center md:aspect-auto md:box-border md:gap-x-2 md:flex md:h-min md:justify-center md:overscroll-x-auto md:overscroll-y-auto md:gap-y-2 md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-min md:overflow-hidden md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
            <div className="static box-content block flex-row shrink justify-normal min-h-0 min-w-0 text-wrap md:relative md:aspect-auto md:box-border md:flex md:flex-col md:shrink-0 md:justify-start md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
              <h6 className="text-black text-[10.72px] font-bold box-content leading-[normal] min-h-0 min-w-0 text-wrap font-times md:text-neutral-900 md:text-base md:font-medium md:aspect-auto md:box-border md:leading-6 md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:text-nowrap md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:font-satoshi">
                Our projects
              </h6>
            </div>
          </div>
        </div>
      </div>
      <div className="box-content block md:aspect-auto md:box-border md:contents md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
        <div className="static box-content block flex-row shrink justify-normal max-w-none min-h-0 min-w-0 w-auto break-normal md:relative md:aspect-auto md:box-border md:flex md:flex-col md:shrink-0 md:justify-start md:max-w-[560px] md:min-h-[auto] md:min-w-[auto] md:break-words md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
          <h2 className="text-black text-2xl font-bold box-content leading-[normal] min-h-0 min-w-0 text-start break-normal font-times md:text-neutral-400 md:text-4xl md:font-medium md:aspect-auto md:box-border md:leading-[44px] md:min-h-[auto] md:min-w-[auto] md:break-words md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:text-left md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:font-satoshi">
            <span className="text-black box-content break-normal md:text-neutral-900 md:aspect-auto md:box-border md:break-words md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">Showcasing our
            </span>
            most remarkable creations
          </h2>
        </div>
      </div>
    </div>
    <div className="relative box-border gap-x-4 grid shrink-0 auto-rows-[minmax(0px,1fr)] grid-cols-[repeat(1,minmax(50px,1fr))] grid-rows-[repeat(2,minmax(0px,1fr))] h-min justify-center max-w-[920px] gap-y-4 w-full px-0 md:gap-x-6 md:grid-cols-[repeat(3,minmax(50px,1fr))] md:gap-y-6 md:px-6">
      <div className="box-content block md:aspect-auto md:box-border md:contents md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
        <div className="static self-auto box-content shrink h-auto justify-self-auto min-h-0 min-w-0 transform-none w-auto md:relative md:self-start md:aspect-auto md:box-border md:shrink-0 md:h-[235px] md:justify-self-start md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:translate-y-16 md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
          <div className="static shadow-none box-content h-auto w-auto rounded-none md:relative md:aspect-auto md:shadow-[rgba(18,18,24,0.1)_0px_4px_8px_-4px,rgba(18,18,24,0.05)_0px_12px_18px_-2px] md:box-border md:h-full md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-2xl after:md:accent-auto after:md:box-border after:md:text-black after:md:block after:md:text-xs after:md:not-italic after:md:normal-nums after:md:font-normal after:md:h-full after:md:tracking-[normal] after:md:leading-[normal] after:md:list-outside after:md:list-disc after:md:absolute after:md:text-start after:md:indent-[0px] after:md:normal-case after:md:visible after:md:w-full after:md:border after:md:border-gray-950/10 after:md:rounded-2xl after:md:border-separate after:md:border-solid after:md:left-0 after:md:top-0 after:md:font-sans_serif">
            <div className="static box-content rounded-none inset-auto md:absolute md:aspect-auto md:box-border md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-2xl md:inset-0">
              <img sizes="max((min(min(100vw, 1200px) - 48px, 920px) - 96px) / 3, 50px)" src="https://c.animaapp.com/mdz8y1wiUxZFZV/assets/sMTYSbL4QzpVHm1UyyQvDNKN0I.png" alt="Photo by Stylokit" className="box-content h-auto object-fill align-middle w-auto rounded-none md:aspect-[auto_1600_/_1367] md:box-border md:h-full md:object-cover md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:align-baseline md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-2xl" />
            </div>
          </div>
        </div>
      </div>
      <div className="box-content block md:aspect-auto md:box-border md:contents md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
        <div className="static self-auto box-content shrink h-auto justify-self-auto min-h-0 min-w-0 transform-none w-auto md:relative md:self-start md:aspect-auto md:box-border md:shrink-0 md:h-[235px] md:justify-self-start md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:translate-y-16 md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
          <div className="static shadow-none box-content h-auto w-auto rounded-none md:relative md:aspect-auto md:shadow-[rgba(18,18,24,0.1)_0px_4px_8px_-4px,rgba(18,18,24,0.05)_0px_12px_18px_-2px] md:box-border md:h-full md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-2xl after:md:accent-auto after:md:box-border after:md:text-black after:md:block after:md:text-xs after:md:not-italic after:md:normal-nums after:md:font-normal after:md:h-full after:md:tracking-[normal] after:md:leading-[normal] after:md:list-outside after:md:list-disc after:md:absolute after:md:text-start after:md:indent-[0px] after:md:normal-case after:md:visible after:md:w-full after:md:border after:md:border-gray-950/10 after:md:rounded-2xl after:md:border-separate after:md:border-solid after:md:left-0 after:md:top-0 after:md:font-sans_serif">
            <div className="static box-content rounded-none inset-auto md:absolute md:aspect-auto md:box-border md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-2xl md:inset-0">
              <img sizes="max((min(min(100vw, 1200px) - 48px, 920px) - 96px) / 3, 50px)" src="https://c.animaapp.com/mdz8y1wiUxZFZV/assets/6vx2gAgbiGxuRFJM5IId43iYhpg.png" alt="Photo by Stylokit" className="box-content h-auto object-fill align-middle w-auto rounded-none md:aspect-[auto_1600_/_1367] md:box-border md:h-full md:object-cover md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:align-baseline md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-2xl" />
            </div>
          </div>
        </div>
      </div>
      <div className="box-content block md:aspect-auto md:box-border md:contents md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
        <div className="static self-auto box-content shrink h-auto justify-self-auto min-h-0 min-w-0 transform-none w-auto md:relative md:self-start md:aspect-auto md:box-border md:shrink-0 md:h-[235px] md:justify-self-start md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:translate-y-16 md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
          <div className="static shadow-none box-content h-auto w-auto rounded-none md:relative md:aspect-auto md:shadow-[rgba(18,18,24,0.1)_0px_4px_8px_-4px,rgba(18,18,24,0.05)_0px_12px_18px_-2px] md:box-border md:h-full md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-2xl after:md:accent-auto after:md:box-border after:md:text-black after:md:block after:md:text-xs after:md:not-italic after:md:normal-nums after:md:font-normal after:md:h-full after:md:tracking-[normal] after:md:leading-[normal] after:md:list-outside after:md:list-disc after:md:absolute after:md:text-start after:md:indent-[0px] after:md:normal-case after:md:visible after:md:w-full after:md:border after:md:border-gray-950/10 after:md:rounded-2xl after:md:border-separate after:md:border-solid after:md:left-0 after:md:top-0 after:md:font-sans_serif">
            <div className="static box-content rounded-none inset-auto md:absolute md:aspect-auto md:box-border md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-2xl md:inset-0">
              <img sizes="max((min(min(100vw, 1200px) - 48px, 920px) - 96px) / 3, 50px)" src="https://c.animaapp.com/mdz8y1wiUxZFZV/assets/36gAbzgyQnEn4HlMqktVKXXzM.png" alt="Photo by Stylokit" className="box-content h-auto object-fill align-middle w-auto rounded-none md:aspect-[auto_1600_/_1367] md:box-border md:h-full md:object-cover md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:align-baseline md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-2xl" />
            </div>
          </div>
        </div>
      </div>
      <div className="box-content block md:aspect-auto md:box-border md:contents md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
        <div className="static self-auto box-content shrink col-start-auto h-auto justify-self-auto min-h-0 min-w-0 transform-none w-auto md:relative md:self-start md:aspect-auto md:box-border md:shrink-0 md:col-start-[span_2] md:h-[235px] md:justify-self-start md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:translate-y-16 md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
          <div className="static shadow-none box-content h-auto w-auto rounded-none md:relative md:aspect-auto md:shadow-[rgba(18,18,24,0.1)_0px_4px_8px_-4px,rgba(18,18,24,0.05)_0px_12px_18px_-2px] md:box-border md:h-full md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-2xl after:md:accent-auto after:md:box-border after:md:text-black after:md:block after:md:text-xs after:md:not-italic after:md:normal-nums after:md:font-normal after:md:h-full after:md:tracking-[normal] after:md:leading-[normal] after:md:list-outside after:md:list-disc after:md:absolute after:md:text-start after:md:indent-[0px] after:md:normal-case after:md:visible after:md:w-full after:md:border after:md:border-gray-950/10 after:md:rounded-2xl after:md:border-separate after:md:border-solid after:md:left-0 after:md:top-0 after:md:font-sans_serif">
            <div className="static box-content rounded-none inset-auto md:absolute md:aspect-auto md:box-border md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-2xl md:inset-0">
              <img sizes="calc(max((min(min(100vw, 1200px) - 48px, 920px) - 96px) / 3, 50px) * 2 + 24px)" src="https://c.animaapp.com/mdz8y1wiUxZFZV/assets/rysJ0r2SxvFZxBizCjXvpTg4CZE.png" alt="" className="box-content h-auto object-fill align-middle w-auto rounded-none md:aspect-[auto_3200_/_1367] md:box-border md:h-full md:object-cover md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:align-baseline md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-2xl" />
            </div>
          </div>
        </div>
      </div>
      <div className="box-content block md:aspect-auto md:box-border md:contents md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
        <div className="static self-auto box-content shrink h-auto justify-self-auto min-h-0 min-w-0 transform-none w-auto md:relative md:self-start md:aspect-auto md:box-border md:shrink-0 md:h-[235px] md:justify-self-start md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:translate-y-16 md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
          <div className="static shadow-none box-content h-auto w-auto rounded-none md:relative md:aspect-auto md:shadow-[rgba(18,18,24,0.1)_0px_4px_8px_-4px,rgba(18,18,24,0.05)_0px_12px_18px_-2px] md:box-border md:h-full md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-2xl after:md:accent-auto after:md:box-border after:md:text-black after:md:block after:md:text-xs after:md:not-italic after:md:normal-nums after:md:font-normal after:md:h-full after:md:tracking-[normal] after:md:leading-[normal] after:md:list-outside after:md:list-disc after:md:absolute after:md:text-start after:md:indent-[0px] after:md:normal-case after:md:visible after:md:w-full after:md:border after:md:border-gray-950/10 after:md:rounded-2xl after:md:border-separate after:md:border-solid after:md:left-0 after:md:top-0 after:md:font-sans_serif">
            <div className="static box-content rounded-none inset-auto md:absolute md:aspect-auto md:box-border md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-2xl md:inset-0">
              <img sizes="max((min(min(100vw, 1200px) - 48px, 920px) - 96px) / 3, 50px)" src="https://c.animaapp.com/mdz8y1wiUxZFZV/assets/5W9dc3487k2e23Xgy0vIvSQpdDg.png" alt="Photo by Stylokit" className="box-content h-auto object-fill align-middle w-auto rounded-none md:aspect-[auto_1600_/_1367] md:box-border md:h-full md:object-cover md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:align-baseline md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-2xl" />
            </div>
          </div>
        </div>
      </div>
      <div className="box-content block md:aspect-auto md:box-border md:contents md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
        <div className="static self-auto box-content shrink h-auto justify-self-auto min-h-0 min-w-0 transform-none w-auto md:relative md:self-start md:aspect-auto md:box-border md:shrink-0 md:h-[235px] md:justify-self-start md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:translate-y-16 md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
          <div className="static shadow-none box-content h-auto w-auto rounded-none md:relative md:aspect-auto md:shadow-[rgba(18,18,24,0.1)_0px_4px_8px_-4px,rgba(18,18,24,0.05)_0px_12px_18px_-2px] md:box-border md:h-full md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-2xl after:md:accent-auto after:md:box-border after:md:text-black after:md:block after:md:text-xs after:md:not-italic after:md:normal-nums after:md:font-normal after:md:h-full after:md:tracking-[normal] after:md:leading-[normal] after:md:list-outside after:md:list-disc after:md:absolute after:md:text-start after:md:indent-[0px] after:md:normal-case after:md:visible after:md:w-full after:md:border after:md:border-gray-950/10 after:md:rounded-2xl after:md:border-separate after:md:border-solid after:md:left-0 after:md:top-0 after:md:font-sans_serif">
            <div className="static box-content rounded-none inset-auto md:absolute md:aspect-auto md:box-border md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-2xl md:inset-0">
              <img sizes="max((min(min(100vw, 1200px) - 48px, 920px) - 96px) / 3, 50px)" src="https://c.animaapp.com/mdz8y1wiUxZFZV/assets/qFvuFrilAAmCZBrHyUsoZktscM.png" alt="Photo by Stylokit" className="box-content h-auto object-fill align-middle w-auto rounded-none md:aspect-[auto_1600_/_1367] md:box-border md:h-full md:object-cover md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:align-baseline md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-2xl" />
            </div>
          </div>
        </div>
      </div>
      <div className="box-content block md:aspect-auto md:box-border md:contents md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
        <div className="static self-auto box-content shrink col-start-auto row-start-auto h-auto justify-self-auto min-h-0 min-w-0 transform-none w-auto md:relative md:self-start md:aspect-auto md:box-border md:shrink-0 md:col-start-[span_2] md:row-start-[span_2] md:h-full md:justify-self-start md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:translate-y-16 md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
          <div className="static shadow-none box-content h-auto w-auto rounded-none md:relative md:aspect-auto md:shadow-[rgba(18,18,24,0.1)_0px_4px_8px_-4px,rgba(18,18,24,0.05)_0px_12px_18px_-2px] md:box-border md:h-full md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-2xl after:md:accent-auto after:md:box-border after:md:text-black after:md:block after:md:text-xs after:md:not-italic after:md:normal-nums after:md:font-normal after:md:h-full after:md:tracking-[normal] after:md:leading-[normal] after:md:list-outside after:md:list-disc after:md:absolute after:md:text-start after:md:indent-[0px] after:md:normal-case after:md:visible after:md:w-full after:md:border after:md:border-gray-950/10 after:md:rounded-2xl after:md:border-separate after:md:border-solid after:md:left-0 after:md:top-0 after:md:font-sans_serif">
            <div className="static box-content rounded-none inset-auto md:absolute md:aspect-auto md:box-border md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-2xl md:inset-0">
              <img sizes="calc(max((min(min(100vw, 1200px) - 48px, 920px) - 96px) / 3, 50px) * 2 + 24px)" src="https://c.animaapp.com/mdz8y1wiUxZFZV/assets/AqfUcDzKyJ9nuBlLjaa550Rzo.png" alt="Photo by Stylokit" className="box-content h-auto object-fill align-middle w-auto rounded-none md:aspect-[auto_2417_/_1812] md:box-border md:h-full md:object-cover md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:align-baseline md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-2xl" />
            </div>
          </div>
        </div>
      </div>
      <div className="box-content block md:aspect-auto md:box-border md:contents md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
        <div className="static self-auto box-content shrink h-auto justify-self-auto min-h-0 min-w-0 transform-none w-auto md:relative md:self-start md:aspect-auto md:box-border md:shrink-0 md:h-[235px] md:justify-self-start md:min-h-[auto] md:min-w-[auto] md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:translate-y-16 md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto]">
          <div className="static shadow-none box-content h-auto w-auto rounded-none md:relative md:aspect-auto md:shadow-[rgba(18,18,24,0.1)_0px_4px_8px_-4px,rgba(18,18,24,0.05)_0px_12px_18px_-2px] md:box-border md:h-full md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-2xl after:md:accent-auto after:md:box-border after:md:text-black after:md:block after:md:text-xs after:md:not-italic after:md:normal-nums after:md:font-normal after:md:h-full after:md:tracking-[normal] after:md:leading-[normal] after:md:list-outside after:md:list-disc after:md:absolute after:md:text-start after:md:indent-[0px] after:md:normal-case after:md:visible after:md:w-full after:md:border after:md:border-gray-950/10 after:md:rounded-2xl after:md:border-separate after:md:border-solid after:md:left-0 after:md:top-0 after:md:font-sans_serif">
            <div className="static box-content rounded-none inset-auto md:absolute md:aspect-auto md:box-border md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-2xl md:inset-0">
              <img sizes="max((min(min(100vw, 1200px) - 48px, 920px) - 96px) / 3, 50px)" src="https://c.animaapp.com/mdz8y1wiUxZFZV/assets/200EOjxIX17rfXaL6YnjWoCHE.png" alt="Photo by Stylokit" className="box-content h-auto object-fill align-middle w-auto rounded-none md:aspect-[auto_1600_/_1367] md:box-border md:h-full md:object-cover md:overscroll-x-auto md:overscroll-y-auto md:snap-align-none md:snap-normal md:snap-none md:decoration-auto md:underline-offset-auto md:align-baseline md:w-full md:[mask-position:0%] md:bg-left-top md:scroll-m-0 md:scroll-p-[auto] md:rounded-2xl" />
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>


    );
};

export default IndexDuplicate1Section__structures7;